CREATE TABLE CONDOM(
    ID_CONDOM INT NOT NULL,
    NAME VARCHAR(100),
    DT_BIRTH DATE,
    CPF CHAR(11)
);

CREATE TABLE COMMOM_AREA(
    ID_COMMON_AREA INT NOT NULL,
    NAME VARCHAR(75),
    DESCRIPTION VARCHAR(300)
);

CREATE TABLE RESERVE(
    ID_RESERVE INT NOT NULL,
    DT_RESERVE DATE,
    ID_CONDOM VARCHAR(255),
    ID_COMMON_AREA VARCHAR(255)
);

ALTER TABLE CONDOM
ADD CONSTRAINT PK_ID_CONDOM PRIMARY KEY (ID_CONDOM);

ALTER TABLE  COMMOM_AREA
ADD CONSTRAINT PK_ID_COMMON_AREA PRIMARY KEY (ID_COMMON_AREA);

ALTER TABLE RESERVE
ADD CONSTRAINT PK_ID_RESERVE PRIMARY KEY (ID_RESERVE);

ALTER TABLE RESERVE
ADD CONSTRAINT FK_ID_CONDOM FOREIGN KEY (ID_CONDOM) REFERENCES CONDOM(ID_CONDOM);

ALTER TABLE RESERVE
ADD CONSTRAINT FK_ID_COMMON_AREA FOREIGN KEY (ID_COMMON_AREA) REFERENCES COMMOM_AREA(ID_COMMON_AREA);